name: CI
on:
  push:
    branches: ["main"]
    tags: ["v*"]
  pull_request:
    branches: ["*"]

jobs:
  macos_build:
    name: MacOS (${{ matrix.OS }})
    strategy:
      fail-fast: true
      matrix:
        OS: ["macos-13", "macos-14"]
    runs-on: ${{ matrix.OS }}
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0 

      - name: Setup
        uses: actions/setup-java@v4
        with:
          java-version: 21
          distribution: temurin
          cache: sbt

      - uses: sbt/setup-sbt@v1

      - name: Tests and build binary
        run: sbt test buildBinary

  linux_build:
    name: Linux (${{ matrix.OS }})
    strategy:
      fail-fast: true
      matrix:
        OS: ["ubuntu-22.04", "ubuntu-22.04-arm"]
    runs-on: ${{ matrix.OS }}
    steps:
    - uses: actions/checkout@v4
      with:
        fetch-depth: 0 

    - uses: actions/setup-java@v4
      with:
        distribution: 'temurin' 
        java-version: '21'
        cache: 'sbt'

    - uses: sbt/setup-sbt@v1

    - name: Tests and build binary
      run: sbt test buildBinary

  mergify-build-checkpoint:
    runs-on: ubuntu-latest
    needs: [linux_build, macos_build]
    steps:
      - name: I only exist to please Mergify :(
        run: echo "It's a sad existence but necessary"

  release:
    needs: [linux_build, macos_build]
    name: Release
    if: startsWith(github.ref, 'refs/tags/v') || (github.ref == 'refs/heads/main')
    runs-on: ubuntu-latest
    env: 
      BINARIES: binaries/
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0 

      - uses: actions/setup-java@v4
        with:
          distribution: 'temurin' 
          java-version: '21'
          cache: 'sbt'

      - uses: sbt/setup-sbt@v1

      - name: Publish
        run: |
          sbt ci-release
        env:
          PGP_PASSPHRASE: ${{ secrets.PGP_PASSPHRASE }}
          PGP_SECRET: ${{ secrets.PGP_SECRET }}
          SONATYPE_PASSWORD: ${{ secrets.SONATYPE_PASSWORD }}
          SONATYPE_USERNAME: ${{ secrets.SONATYPE_USERNAME }}

